display_title: Power Gird Lib
display_tagline: Benchmarks for Validating of Power System Algorithms
github_repo_id: power-grid-lib
download_zip:
download_tar:
admin_name: Carleton Coffrin
admin_email: carleton [at] coffrin [dot] com
admin_github_username: ccoffrin
